#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPim.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class BancoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
        internal object tbQuarto;

        #region Extensibility Method Definitions
        partial void OnCreated();
    partial void InserttbHospede(tbHospede instance);
    partial void UpdatetbHospede(tbHospede instance);
    partial void DeletetbHospede(tbHospede instance);
    partial void InserttbFuncionario(tbFuncionario instance);
    partial void UpdatetbFuncionario(tbFuncionario instance);
    partial void DeletetbFuncionario(tbFuncionario instance);
    partial void InserttbPagamento(tbPagamento instance);
    partial void UpdatetbPagamento(tbPagamento instance);
    partial void DeletetbPagamento(tbPagamento instance);
    partial void InserttbQuarto(tbQuarto instance);
    partial void UpdatetbQuarto(tbQuarto instance);
    partial void DeletetbQuarto(tbQuarto instance);
    partial void InserttbReserva(tbReserva instance);
    partial void UpdatetbReserva(tbReserva instance);
    partial void DeletetbReserva(tbReserva instance);
    partial void InserttbServico(tbServico instance);
    partial void UpdatetbServico(tbServico instance);
    partial void DeletetbServico(tbServico instance);
    #endregion
		
		public BancoDataContext() : 
				base(global::ProjetoPim.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbHospede> tbHospedes
		{
			get
			{
				return this.GetTable<tbHospede>();
			}
		}
		
		public System.Data.Linq.Table<tbFuncionario> tbFuncionarios
		{
			get
			{
				return this.GetTable<tbFuncionario>();
			}
		}
		
		public System.Data.Linq.Table<tbPagamento> tbPagamentos
		{
			get
			{
				return this.GetTable<tbPagamento>();
			}
		}
		
		public System.Data.Linq.Table<tbQuarto> tbQuartos
		{
			get
			{
				return this.GetTable<tbQuarto>();
			}
		}
		
		public System.Data.Linq.Table<tbReserva> tbReservas
		{
			get
			{
				return this.GetTable<tbReserva>();
			}
		}
		
		public System.Data.Linq.Table<tbServico> tbServicos
		{
			get
			{
				return this.GetTable<tbServico>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHospede")]
	public partial class tbHospede : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdHospede;
		
		private string _Nome;
		
		private string _Cpf;
		
		private string _Email;
		
		private string _Telefone;
		
		private System.DateTime _DtNasc;
		
		private string _Senha;
		
		private EntitySet<tbReserva> _tbReservas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHospedeChanging(int value);
    partial void OnIdHospedeChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCpfChanging(string value);
    partial void OnCpfChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnDtNascChanging(System.DateTime value);
    partial void OnDtNascChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    #endregion
		
		public tbHospede()
		{
			this._tbReservas = new EntitySet<tbReserva>(new Action<tbReserva>(this.attach_tbReservas), new Action<tbReserva>(this.detach_tbReservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHospede", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdHospede
		{
			get
			{
				return this._IdHospede;
			}
			set
			{
				if ((this._IdHospede != value))
				{
					this.OnIdHospedeChanging(value);
					this.SendPropertyChanging();
					this._IdHospede = value;
					this.SendPropertyChanged("IdHospede");
					this.OnIdHospedeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpf", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Cpf
		{
			get
			{
				return this._Cpf;
			}
			set
			{
				if ((this._Cpf != value))
				{
					this.OnCpfChanging(value);
					this.SendPropertyChanging();
					this._Cpf = value;
					this.SendPropertyChanged("Cpf");
					this.OnCpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtNasc", DbType="DateTime NOT NULL")]
		public System.DateTime DtNasc
		{
			get
			{
				return this._DtNasc;
			}
			set
			{
				if ((this._DtNasc != value))
				{
					this.OnDtNascChanging(value);
					this.SendPropertyChanging();
					this._DtNasc = value;
					this.SendPropertyChanged("DtNasc");
					this.OnDtNascChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbHospede_tbReserva", Storage="_tbReservas", ThisKey="IdHospede", OtherKey="IdHospede")]
		public EntitySet<tbReserva> tbReservas
		{
			get
			{
				return this._tbReservas;
			}
			set
			{
				this._tbReservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbReservas(tbReserva entity)
		{
			this.SendPropertyChanging();
			entity.tbHospede = this;
		}
		
		private void detach_tbReservas(tbReserva entity)
		{
			this.SendPropertyChanging();
			entity.tbHospede = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFuncionario")]
	public partial class tbFuncionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFuncionario;
		
		private string _Nome;
		
		private string _Email;
		
		private string _Telefone;
		
		private System.DateTime _DtNasc;
		
		private string _Senha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnDtNascChanging(System.DateTime value);
    partial void OnDtNascChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    #endregion
		
		public tbFuncionario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtNasc", DbType="DateTime NOT NULL")]
		public System.DateTime DtNasc
		{
			get
			{
				return this._DtNasc;
			}
			set
			{
				if ((this._DtNasc != value))
				{
					this.OnDtNascChanging(value);
					this.SendPropertyChanging();
					this._DtNasc = value;
					this.SendPropertyChanged("DtNasc");
					this.OnDtNascChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPagamento")]
	public partial class tbPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPagamento;
		
		private string _Tipo;
		
		private decimal _TotalPagamento;
		
		private int _IdReserva;
		
		private int _IdServico;
		
		private EntityRef<tbReserva> _tbReserva;
		
		private EntityRef<tbServico> _tbServico;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPagamentoChanging(int value);
    partial void OnIdPagamentoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnTotalPagamentoChanging(decimal value);
    partial void OnTotalPagamentoChanged();
    partial void OnIdReservaChanging(int value);
    partial void OnIdReservaChanged();
    partial void OnIdServicoChanging(int value);
    partial void OnIdServicoChanged();
    #endregion
		
		public tbPagamento()
		{
			this._tbReserva = default(EntityRef<tbReserva>);
			this._tbServico = default(EntityRef<tbServico>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPagamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPagamento
		{
			get
			{
				return this._IdPagamento;
			}
			set
			{
				if ((this._IdPagamento != value))
				{
					this.OnIdPagamentoChanging(value);
					this.SendPropertyChanging();
					this._IdPagamento = value;
					this.SendPropertyChanged("IdPagamento");
					this.OnIdPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPagamento", DbType="Decimal(20,0) NOT NULL")]
		public decimal TotalPagamento
		{
			get
			{
				return this._TotalPagamento;
			}
			set
			{
				if ((this._TotalPagamento != value))
				{
					this.OnTotalPagamentoChanging(value);
					this.SendPropertyChanging();
					this._TotalPagamento = value;
					this.SendPropertyChanged("TotalPagamento");
					this.OnTotalPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReserva", DbType="Int NOT NULL")]
		public int IdReserva
		{
			get
			{
				return this._IdReserva;
			}
			set
			{
				if ((this._IdReserva != value))
				{
					if (this._tbReserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdReservaChanging(value);
					this.SendPropertyChanging();
					this._IdReserva = value;
					this.SendPropertyChanged("IdReserva");
					this.OnIdReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServico", DbType="Int NOT NULL")]
		public int IdServico
		{
			get
			{
				return this._IdServico;
			}
			set
			{
				if ((this._IdServico != value))
				{
					if (this._tbServico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdServicoChanging(value);
					this.SendPropertyChanging();
					this._IdServico = value;
					this.SendPropertyChanged("IdServico");
					this.OnIdServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbReserva_tbPagamento", Storage="_tbReserva", ThisKey="IdReserva", OtherKey="IdReserva", IsForeignKey=true)]
		public tbReserva tbReserva
		{
			get
			{
				return this._tbReserva.Entity;
			}
			set
			{
				tbReserva previousValue = this._tbReserva.Entity;
				if (((previousValue != value) 
							|| (this._tbReserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbReserva.Entity = null;
						previousValue.tbPagamentos.Remove(this);
					}
					this._tbReserva.Entity = value;
					if ((value != null))
					{
						value.tbPagamentos.Add(this);
						this._IdReserva = value.IdReserva;
					}
					else
					{
						this._IdReserva = default(int);
					}
					this.SendPropertyChanged("tbReserva");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbServico_tbPagamento", Storage="_tbServico", ThisKey="IdServico", OtherKey="IdServico", IsForeignKey=true)]
		public tbServico tbServico
		{
			get
			{
				return this._tbServico.Entity;
			}
			set
			{
				tbServico previousValue = this._tbServico.Entity;
				if (((previousValue != value) 
							|| (this._tbServico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbServico.Entity = null;
						previousValue.tbPagamentos.Remove(this);
					}
					this._tbServico.Entity = value;
					if ((value != null))
					{
						value.tbPagamentos.Add(this);
						this._IdServico = value.IdServico;
					}
					else
					{
						this._IdServico = default(int);
					}
					this.SendPropertyChanged("tbServico");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbQuarto")]
	public partial class tbQuarto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdQuarto;
		
		private string _Descricao;
		
		private decimal _ValorDiaria;
		
		private EntitySet<tbReserva> _tbReservas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdQuartoChanging(int value);
    partial void OnIdQuartoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorDiariaChanging(decimal value);
    partial void OnValorDiariaChanged();
    #endregion
		
		public tbQuarto()
		{
			this._tbReservas = new EntitySet<tbReserva>(new Action<tbReserva>(this.attach_tbReservas), new Action<tbReserva>(this.detach_tbReservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuarto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdQuarto
		{
			get
			{
				return this._IdQuarto;
			}
			set
			{
				if ((this._IdQuarto != value))
				{
					this.OnIdQuartoChanging(value);
					this.SendPropertyChanging();
					this._IdQuarto = value;
					this.SendPropertyChanged("IdQuarto");
					this.OnIdQuartoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorDiaria", DbType="Decimal(18,0) NOT NULL")]
		public decimal ValorDiaria
		{
			get
			{
				return this._ValorDiaria;
			}
			set
			{
				if ((this._ValorDiaria != value))
				{
					this.OnValorDiariaChanging(value);
					this.SendPropertyChanging();
					this._ValorDiaria = value;
					this.SendPropertyChanged("ValorDiaria");
					this.OnValorDiariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbQuarto_tbReserva", Storage="_tbReservas", ThisKey="IdQuarto", OtherKey="IdQuarto")]
		public EntitySet<tbReserva> tbReservas
		{
			get
			{
				return this._tbReservas;
			}
			set
			{
				this._tbReservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbReservas(tbReserva entity)
		{
			this.SendPropertyChanging();
			entity.tbQuarto = this;
		}
		
		private void detach_tbReservas(tbReserva entity)
		{
			this.SendPropertyChanging();
			entity.tbQuarto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbReserva")]
	public partial class tbReserva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReserva;
		
		private System.DateTime _DtEntrada;
		
		private System.DateTime _DtSaida;
		
		private string _StatusReserva;
		
		private int _IdQuarto;
		
		private int _IdHospede;
		
		private EntitySet<tbPagamento> _tbPagamentos;
		
		private EntitySet<tbServico> _tbServicos;
		
		private EntityRef<tbHospede> _tbHospede;
		
		private EntityRef<tbQuarto> _tbQuarto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdReservaChanging(int value);
    partial void OnIdReservaChanged();
    partial void OnDtEntradaChanging(System.DateTime value);
    partial void OnDtEntradaChanged();
    partial void OnDtSaidaChanging(System.DateTime value);
    partial void OnDtSaidaChanged();
    partial void OnStatusReservaChanging(string value);
    partial void OnStatusReservaChanged();
    partial void OnIdQuartoChanging(int value);
    partial void OnIdQuartoChanged();
    partial void OnIdHospedeChanging(int value);
    partial void OnIdHospedeChanged();
    #endregion
		
		public tbReserva()
		{
			this._tbPagamentos = new EntitySet<tbPagamento>(new Action<tbPagamento>(this.attach_tbPagamentos), new Action<tbPagamento>(this.detach_tbPagamentos));
			this._tbServicos = new EntitySet<tbServico>(new Action<tbServico>(this.attach_tbServicos), new Action<tbServico>(this.detach_tbServicos));
			this._tbHospede = default(EntityRef<tbHospede>);
			this._tbQuarto = default(EntityRef<tbQuarto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReserva", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdReserva
		{
			get
			{
				return this._IdReserva;
			}
			set
			{
				if ((this._IdReserva != value))
				{
					this.OnIdReservaChanging(value);
					this.SendPropertyChanging();
					this._IdReserva = value;
					this.SendPropertyChanged("IdReserva");
					this.OnIdReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtEntrada", DbType="DateTime NOT NULL")]
		public System.DateTime DtEntrada
		{
			get
			{
				return this._DtEntrada;
			}
			set
			{
				if ((this._DtEntrada != value))
				{
					this.OnDtEntradaChanging(value);
					this.SendPropertyChanging();
					this._DtEntrada = value;
					this.SendPropertyChanged("DtEntrada");
					this.OnDtEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtSaida", DbType="DateTime NOT NULL")]
		public System.DateTime DtSaida
		{
			get
			{
				return this._DtSaida;
			}
			set
			{
				if ((this._DtSaida != value))
				{
					this.OnDtSaidaChanging(value);
					this.SendPropertyChanging();
					this._DtSaida = value;
					this.SendPropertyChanged("DtSaida");
					this.OnDtSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusReserva", DbType="VarChar(100)")]
		public string StatusReserva
		{
			get
			{
				return this._StatusReserva;
			}
			set
			{
				if ((this._StatusReserva != value))
				{
					this.OnStatusReservaChanging(value);
					this.SendPropertyChanging();
					this._StatusReserva = value;
					this.SendPropertyChanged("StatusReserva");
					this.OnStatusReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuarto", DbType="Int NOT NULL")]
		public int IdQuarto
		{
			get
			{
				return this._IdQuarto;
			}
			set
			{
				if ((this._IdQuarto != value))
				{
					if (this._tbQuarto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdQuartoChanging(value);
					this.SendPropertyChanging();
					this._IdQuarto = value;
					this.SendPropertyChanged("IdQuarto");
					this.OnIdQuartoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHospede", DbType="Int NOT NULL")]
		public int IdHospede
		{
			get
			{
				return this._IdHospede;
			}
			set
			{
				if ((this._IdHospede != value))
				{
					if (this._tbHospede.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdHospedeChanging(value);
					this.SendPropertyChanging();
					this._IdHospede = value;
					this.SendPropertyChanged("IdHospede");
					this.OnIdHospedeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbReserva_tbPagamento", Storage="_tbPagamentos", ThisKey="IdReserva", OtherKey="IdReserva")]
		public EntitySet<tbPagamento> tbPagamentos
		{
			get
			{
				return this._tbPagamentos;
			}
			set
			{
				this._tbPagamentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbReserva_tbServico", Storage="_tbServicos", ThisKey="IdReserva", OtherKey="IdReserva")]
		public EntitySet<tbServico> tbServicos
		{
			get
			{
				return this._tbServicos;
			}
			set
			{
				this._tbServicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbHospede_tbReserva", Storage="_tbHospede", ThisKey="IdHospede", OtherKey="IdHospede", IsForeignKey=true)]
		public tbHospede tbHospede
		{
			get
			{
				return this._tbHospede.Entity;
			}
			set
			{
				tbHospede previousValue = this._tbHospede.Entity;
				if (((previousValue != value) 
							|| (this._tbHospede.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbHospede.Entity = null;
						previousValue.tbReservas.Remove(this);
					}
					this._tbHospede.Entity = value;
					if ((value != null))
					{
						value.tbReservas.Add(this);
						this._IdHospede = value.IdHospede;
					}
					else
					{
						this._IdHospede = default(int);
					}
					this.SendPropertyChanged("tbHospede");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbQuarto_tbReserva", Storage="_tbQuarto", ThisKey="IdQuarto", OtherKey="IdQuarto", IsForeignKey=true)]
		public tbQuarto tbQuarto
		{
			get
			{
				return this._tbQuarto.Entity;
			}
			set
			{
				tbQuarto previousValue = this._tbQuarto.Entity;
				if (((previousValue != value) 
							|| (this._tbQuarto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbQuarto.Entity = null;
						previousValue.tbReservas.Remove(this);
					}
					this._tbQuarto.Entity = value;
					if ((value != null))
					{
						value.tbReservas.Add(this);
						this._IdQuarto = value.IdQuarto;
					}
					else
					{
						this._IdQuarto = default(int);
					}
					this.SendPropertyChanged("tbQuarto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPagamentos(tbPagamento entity)
		{
			this.SendPropertyChanging();
			entity.tbReserva = this;
		}
		
		private void detach_tbPagamentos(tbPagamento entity)
		{
			this.SendPropertyChanging();
			entity.tbReserva = null;
		}
		
		private void attach_tbServicos(tbServico entity)
		{
			this.SendPropertyChanging();
			entity.tbReserva = this;
		}
		
		private void detach_tbServicos(tbServico entity)
		{
			this.SendPropertyChanging();
			entity.tbReserva = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbServico")]
	public partial class tbServico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdServico;
		
		private string _Tipo;
		
		private decimal _Valor;
		
		private int _IdReserva;
		
		private EntitySet<tbPagamento> _tbPagamentos;
		
		private EntityRef<tbReserva> _tbReserva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdServicoChanging(int value);
    partial void OnIdServicoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnIdReservaChanging(int value);
    partial void OnIdReservaChanged();
    #endregion
		
		public tbServico()
		{
			this._tbPagamentos = new EntitySet<tbPagamento>(new Action<tbPagamento>(this.attach_tbPagamentos), new Action<tbPagamento>(this.detach_tbPagamentos));
			this._tbReserva = default(EntityRef<tbReserva>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServico", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdServico
		{
			get
			{
				return this._IdServico;
			}
			set
			{
				if ((this._IdServico != value))
				{
					this.OnIdServicoChanging(value);
					this.SendPropertyChanging();
					this._IdServico = value;
					this.SendPropertyChanged("IdServico");
					this.OnIdServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(18,0) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReserva", DbType="Int NOT NULL")]
		public int IdReserva
		{
			get
			{
				return this._IdReserva;
			}
			set
			{
				if ((this._IdReserva != value))
				{
					if (this._tbReserva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdReservaChanging(value);
					this.SendPropertyChanging();
					this._IdReserva = value;
					this.SendPropertyChanged("IdReserva");
					this.OnIdReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbServico_tbPagamento", Storage="_tbPagamentos", ThisKey="IdServico", OtherKey="IdServico")]
		public EntitySet<tbPagamento> tbPagamentos
		{
			get
			{
				return this._tbPagamentos;
			}
			set
			{
				this._tbPagamentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbReserva_tbServico", Storage="_tbReserva", ThisKey="IdReserva", OtherKey="IdReserva", IsForeignKey=true)]
		public tbReserva tbReserva
		{
			get
			{
				return this._tbReserva.Entity;
			}
			set
			{
				tbReserva previousValue = this._tbReserva.Entity;
				if (((previousValue != value) 
							|| (this._tbReserva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbReserva.Entity = null;
						previousValue.tbServicos.Remove(this);
					}
					this._tbReserva.Entity = value;
					if ((value != null))
					{
						value.tbServicos.Add(this);
						this._IdReserva = value.IdReserva;
					}
					else
					{
						this._IdReserva = default(int);
					}
					this.SendPropertyChanged("tbReserva");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPagamentos(tbPagamento entity)
		{
			this.SendPropertyChanging();
			entity.tbServico = this;
		}
		
		private void detach_tbPagamentos(tbPagamento entity)
		{
			this.SendPropertyChanging();
			entity.tbServico = null;
		}
	}
}
#pragma warning restore 1591
